### ISSUE TITLE
Maintenance Status

### ISSUE THREAD

**Issue by out-dev** [trutoo/event-bus#100]
### What is hard to understand or you feel lacks information? Please describe.

Hello all, I am very interested whether this repository is still up-to-date and maintained? I am very interested in using it :-). What is the current maintenance status?

### Describe your current understanding

Hopefully the answer is just YES still maintained just no need to change smth. :-)

### Describe the improvement you'd like

Hopefully the answer is just YES still maintained just no need to change smth. :-)

**Comment by Swiftwork** [comment]
Hi @out-dev,

Yes, the project is still actively maintained. However, it is considered feature complete, so no new additions will be made from our side unless a relevant feature request is submitted. The existing version on npm should work without any issues.

I updated to the latest patch version of json5, but the build failed due to a change in GitHub's API requiring new authorization. Despite this, the code maintains 100% test coverage.

**Comment by out-dev** [comment]
Perfect ❤️  Thanks a lot

**Comment by Swiftwork** [comment]
A little status update for you @out-dev. All dependencies have been brought up to the latest version and a new build has gone out which stripped away a little more code from the ESM package in favor of importing it. We will no longer publish updates to the GitHub package repository and suggest everyone use the `npm` version going forward. This is to simplify the release process.
