### ISSUE TITLE
Documentation with better examples

### ISSUE THREAD

**Issue by aggmoulik** [trutoo/event-bus#79]
**What is hard to understand or you feel lacks information? Please describe.**
I don't understand the need for the package for microframeworks, can we have more clear documentation around the product. I can't find examples to implement or even the architecture of a system that package is trying to solve, as well as the website is not available.

**Describe your current understanding**
It looks like a pub-sub mechanism for microservices.

**Describe the improvement you'd like**
A clear detailed documentation website.

**Comment by aggmoulik** [comment]
@Swiftwork Can we look into the maintenance of the project as I haven't seen much here.

**Comment by Swiftwork** [comment]
Hi @aggmoulik, thank you for reaching out.

The documentation, as you probably have seen, is all written in the [readme](https://github.com/trutoo/event-bus/blob/master/README.md). I have tried to capture the essence in the [purpose section](https://github.com/trutoo/event-bus/blob/master/README.md#purpose). Three examples in React, Angular and basic Web Components in the [usage section](https://github.com/trutoo/event-bus/blob/master/README.md#usage). And finally, every interaction with the library can be found in the [API section](https://github.com/trutoo/event-bus/blob/master/README.md#api). While it isn't an external website I believed it covered all common use-cases, but maybe that isn't the case. Is there a certain section you feel requires extra attention?

While admittedly it isn't the most elegant way to demonstrate the project, [GitHub Pages](https://trutoo.github.io/event-bus/) found in the right sidebar serves as this function if you open the browser's debug tools. Another great way to learn how this tool works is to read the [commented code](https://github.com/trutoo/event-bus/blob/master/src/event-bus.ts) or to look at the [tests](https://github.com/trutoo/event-bus/blob/master/src/event-bus.spec.ts)

To address the question regarding the need, I think that is more dependent on your use-case and platform architecture. For me, it was created as a simple communication channel for lazy-loaded components that did not have a shared state. An example of this is two teams creating two widgets in different frameworks but displayed on the same page and interacting with each other. Think of Google Maps; where the searchable sidebar and the map display would be separate code-bases, but still require interaction.

The final question regarding maintenance is valid, but as it stands now the project is feature complete. It aims to maintain itself as it has 98% code coverage for test and renovate runs weekly to make sure dependencies are up to date to patch security vulnerabilities. Occasionally the pipeline does fail due to a larger dependency update is found that does not pass the tests or GitHub changes the pipeline syntax, but this should not affect the published package. I will look into merging the outstanding pull requests and correcting the pipeline when I have some spare time but don't let this discourage you from trying out the package 😄
