### ISSUE TITLE
nt._subscriptions[_e][rt] is not a function at publish

### ISSUE THREAD

**Issue by vctqs1** [trutoo/event-bus#95]
**Describe the bug**

**To Reproduce**
I was trying able to call subscription and publish method in time unsubscribe just call
and that lead to race condition tand appear error message like this 
```
nt._subscriptions[_e][rt] is not a function TypeError: nt._subscriptions[_e][rt] is not a function ...
at Array.forEach (<anonymous>) at et.publish (https://administration.manabie.net/statics/index.2a14e4bd.js:50:3397)
```
mean that can catch `this._subscriptions[channel][id];` at this step is fn and exec it 
so i would like to add a validation step to check `typeof this._subscriptions[channel][id] === function` before exec at https://github.com/trutoo/event-bus/blob/master/src/event-bus.ts#L141

**Expected behavior**
Throw error if callback is not a function before exec it 

**Additional context**

**Comment by Swiftwork** [comment]
Hi @vctqs1, thank you for your contribution!

I don't understand why you are getting the error above. When checking the lines in the test file regarding publishing https://github.com/trutoo/event-bus/blob/v2.1.1/src/event-bus.spec.ts#L153-L173 we can see that you don't need to register before calling publish. The intention is not to require calling `register` before `publish` as `register` is an optional type-safety feature only.

Regarding `subscribe` we are also already safeguarding against setting a non-function as a callback and you can see it creates the channel if it doesn't exist. https://github.com/trutoo/event-bus/blob/v2.1.1/src/event-bus.ts#L112-L118

Finally, in the `publish` method, the extraction of callbacks is already using `Object.keys` which will return all properties in the channel and then filter out any beginning with `__` as these are considered private. https://github.com/trutoo/event-bus/blob/v2.1.1/src/event-bus.ts#L141. With that knowledge, my assumption is that the error you are getting is due to something other than a function being stored in the subscriptions array. How I don't understand, maybe you have another library adding properties to Object prototypes.

Could you run the following before or after you get the error and post your results here? You can replace `window.eventBus._subscriptions` with your instance `myEventBus._subscriptions` if you created your own defined in the [installation guide](https://github.com/trutoo/event-bus#installation).
```js
JSON.stringify(window.eventBus._subscriptions, (_, val) => (typeof val === 'function') ? '' + val : val);
```

Kind Regards
Erik Hughes

**Comment by vctqs1** [comment]
sorry for the late response, seems my app don't inject eventBus in window, you can see the below image
![image](https://user-images.githubusercontent.com/30227910/192193694-c4da3ed0-4d7e-4c70-b655-b22b104ba7bc.png)

but i was trying to add a console into publish step, you can check here and see the result
![image](https://user-images.githubusercontent.com/30227910/192195268-6cc99457-bff2-49e4-91b3-2dc3084edd1a.png)

in `this._subscriptions[channel]` the current id is `2` but the publish method was call `3` that why it appears  error
![image](https://user-images.githubusercontent.com/30227910/192195671-ff1772d2-68e1-4c0a-af31-3c442bc982ca.png)

**Comment by vctqs1** [comment]
@Swiftwork hii, could u help have a look above message. thank you so much

**Comment by Swiftwork** [comment]
Hi @vctqs1,

Sorry for the delay in response. My company is currently publishing a release of another project which is consuming a lot of my time. Regarding the above, unfortunately, there isn't enough information there for me to decipher what is causing your issue. Are you able to share your project or do a reproduction in something like https://codesandbox.io/. If not share the entire project, maybe you can paste some code here so that I can see what you are calling.

Looking at your console log I think you are running into the issue where you log an object and then expand it later in the console. The issue with doing this is that objects are mutable in JavaScript so you will end up with different properties in the object if they have had time to change before you click it. Try changing your log above from:

```js
console.log("not a function", _this._subscriptions[channel], id)
```
to:
```js
console.log("not a function", JSON.stringify(_this._subscriptions[channel], (_, val) => (typeof val === 'function') ? '' + val : val, 2), id)
```
And then paste that result here as well.

Kind Regards
Erik Hughes

**Comment by vctqs1** [comment]
Hi thank you @Swiftwork , here is the log 
```
not a function {
  "2": "(detail) => {\n      handleNetworkErrors(detail);\n    }",
  "__schema": {
    "type": "object",
    "properties": {
      "detail": {
        "type": "object",
        "properties": {
          "code": {
            "type": "number"
          },
          "props": {
            "type": "object",
            "properties": {
              "error": {},
              "errorInfo": {}
            },
            "required": [
              "error",
              "errorInfo"
            ],
            "additionalProperties": false
          }
        },
        "required": [
          "props"
        ],
        "additionalProperties": false
      },
      "type": {
        "type": "string",
        "enum": [
          "root",
          "adobo",
          "architecture",
          "calendar",
          "communication",
          "lesson",
          "payment",
          "syllabus",
          "timesheet",
          "user"
        ]
      }
    },
    "required": [
      "detail",
      "type"
    ],
    "additionalProperties": false
  },
  "__replay": {
    "detail": {
      "code": 2,
      "props": {
        "error": {
          "name": "ra.common.cannotLoadPage",
          "message": "Http response at 400 or 500 level"
        },
        "errorInfo": {
          "componentStack": "Http response at 400 or 500 level"
        }
      }
    },
    "type": "root"
  }
} 3
```

**Comment by Swiftwork** [comment]
@vctqs1 Thank you for the console.log. My statement:

> Looking at your console log I think you are running into the issue where you log an object and then expand it later in the console. The issue with doing this is that objects are mutable in JavaScript so you will end up with different properties in the object if they have had time to change before you click it.

Was not accurate to your situation and it does look like the function is missing even though the loop doesn't think so. I can add a safeguard to avoid calling missing functions but I would like to understand why this is happening first. Are you able to share your code or create a reproducible demo at https://codesandbox.io/?

**Comment by vctqs1** [comment]
@Swiftwork ahh let me try to reproduce via small demo. But it's not easy :d. I think it can take few days. Please wait for me 

Thank you

**Comment by vctqs1** [comment]
> Was not accurate to your situation and it does look like the function is missing even though the loop doesn't think so

But just let u know `cleanup` fn was interspersed in publishing time. 

I'm trying to change [this block L139-L141](https://github.com/trutoo/event-bus/blob/master/src/event-bus.ts#L139-L141)  to 
```
const arrs = Object.keys(this._subscriptions[channel]).filter((key) => !key.startsWith('__'));
    console.log('========before publish channel', channel, 'arrs', arrs);

    arrs.forEach((id) => {
      console.log(
        '========publish channel',
        channel,
        'id',
        id,
        'payload',
        payload,
        'callback',
        this._subscriptions[channel][id],
      );

      return this._subscriptions[channel][id]({ channel, payload });
    });
```
and add 1 console.log before call `delete this._subscriptions[channel][id] in unsubcribe method` [here](https://github.com/trutoo/event-bus/blob/master/src/event-bus.ts#L118-L121) to 
```
unsubscribe: function () { 
              delete _this._subscriptions[channel][id];
              console.log(
                '========after unsubcribe channel',
                channel,
                'id',
                id,
                JSON.stringify(_this._subscriptions[channel], (_, val) => (typeof val === 'function' ? '' + val : val), 2),
                id,
              );
              return 
             },
```
And see that in console tab it was call and propms look like 
```
========before publish channel networkError arrs  Array [ "2", "3" ]
========publish channel networkError id 2 payload  Object { detail: {…}, type: "root" } callback  function sub(detail)
```
then immediately after that show an unsubscribe message before going to call to `id 3`, and unsubscribe method was put it in `cleanup` fn of React app
```
========after unsubcribe channel networkError id 3 {
```
then continue to exec the next item of arrs.forEach
```
========publish channel networkError id 3 payload Object { detail: {…}, type: "root" } callback undefined
```
![image](https://user-images.githubusercontent.com/30227910/193509655-70006630-96c0-40c7-9af4-47864e92a2cb.png)
![image](https://user-images.githubusercontent.com/30227910/193509785-8d5faada-37b0-453f-8915-97516afc5045.png)



![image](https://user-images.githubusercontent.com/30227910/193509373-6f65e236-328e-4f87-9056-032a86b82262.png)
![image](https://user-images.githubusercontent.com/30227910/193509385-24d6b6a5-0a1b-44e4-8cd8-7b560d89d70e.png)

**Comment by Swiftwork** [comment]
@vctqs1 Thank you for your explanation. I now understand what is happening. The subscriptions array is being mutated in the middle of the forEach loop. This is rare, but I can see that it is a problem if multiple fragments are working with the same PubSub. I will attempt to release a fix today if time allows. I will put in some safeguards and attempt to replicate the issue in a test.

**Comment by vctqs1** [comment]
@Swiftwork thank you so much, I was try to catch this by the way check `typeof` of callback before call it in this PR https://github.com/trutoo/event-bus/pull/96/files

I'm happy if I can help you somehow. thank you

**Comment by Swiftwork** [comment]
@vctqs1 Please give version 2.2.0 a try and report back if this resolves your issue.

**Comment by vctqs1** [comment]
its work perfect thank you so much @Swiftwork
